---
# A set of little config changes for harding the ssh service
- name: Set sshd port to a non-standard port
  lineinfile:
    regexp: 'Port '
    line: "Port {{ base_ssh_port }}"
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd
  when: base_ssh_port_change == "true"


- name: Disable ssh root login
  lineinfile:
    regexp: 'PermitRootLogin '
    line: 'PermitRootLogin no'
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd

- name: Disable PasswordAuthentication
  lineinfile:
    regexp: 'PasswordAuthentication '
    line: 'PasswordAuthentication no'
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd

- name: Sets AllowUsers to only konekto
  lineinfile:
    line: 'AllowUsers admin deployer vagrant'
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd
