---

- name: "Ensure that firewalld is installed."
  yum:
    name: firewalld
    state: latest

- name: "Ensure that defined services are open for incoming connections"
  firewalld:
    service: "{{item}}"
    permanent: true
    state: enabled
  loop: "{{ base_firewalld_open_services }}"
  notify:
    - restart firewalld service
  when: base_firewalld_open_services

- name: "Ensure that defined ports are open for incoming connections"
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
  loop: "{{ base_firewalld_open_ports }}"
  notify:
    - restart firewalld service
  when: base_firewalld_open_ports

- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: true
