---
# Add the developers keys to admin and deployer
- name: Adds ssh keys for authorized keys
  authorized_key:
    user: "{{item}}"
    state: present
    key: "{{ base_ssh_keys_url }}"
  loop:
    - deployer
    - admin
  when: base_ssh_keys_url != "false"
