- set_fact:
    users: "{{ base_default_users + base_additional_users }}"

- name: Create user admin and deployer
  user:
    name: "{{ item }}"
    append: yes
    shell: /bin/bash
  loop: "{{users}}"

- name: Create user admin and deployer .ssh folder
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
  loop: "{{users}}"

- name: Create user admin and deployer authorized keys
  copy:
    content: ""
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    group: "{{item}}"
    owner: "{{item}}"
    mode: 0644
    force: no
  loop: "{{users}}"

- name: Create ssh key for all users
  command: "ssh-keygen -b 2048 -t rsa -f /home/{{ item }}/.ssh/id_rsa -q -N \"\""
  args:
    creates: "/home/{{ item }}/.ssh/id_rsa"
  loop: "{{users}}"

- name: "Correct permissions of ssh keys"
  file:
    path: "/home/{{ item }}/.ssh/id_rsa"
    mode: 0600
    owner: "{{ item }}"
    state: file
  loop: "{{users}}"

