- set_fact:
    users: "{{ base_default_users + base_additional_users }}"

- name: Create user admin and deployer
  user:
    name: "{{ item }}"
    append: yes
    shell: /bin/bash
  loop: "{{users}}"


- name: Create user admin and deployer .ssh folder
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
  loop: "{{users}}"

- name: Create user admin and deployer authorized keys
  copy:
    content: ""
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    group: "{{item}}"
    owner: "{{item}}"
    mode: 0644
    force: no
  loop: "{{users}}"

  ##Due to problems with the root password change logic comment this out.

#- name: "Load root password in memory"
#  slurp:
#    src: /home/admin/.root_password
#  register: root_password_base64
#
#- set_fact:
#    root_password: "{{ root_password_base64['content'] | b64decode }}"
#
#- name: Set new password for root user
#  shell: "echo \"root:{{root_password}}\" | chpasswd"
