- set_fact:
    users: "{{ base_default_users + base_additional_users }}"

- name: Create user admin and deployer
  user:
    name: "{{ item }}"
    append: yes
    shell: /bin/bash
  loop: "{{users}}"


- name: Create user admin and deployer .ssh folder
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
  loop: "{{users}}"

- name: Create user admin and deployer authorized keys
  copy:
    content: ""
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    group: "{{item}}"
    owner: "{{item}}"
    mode: 0644
    force: no
  loop: "{{users}}"

- name: Create root password
  shell: "head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20"
  args:
    creates: /home/admin/.root_password
  register: root_password

- command: "python -c 'import crypt; print(crypt.crypt(\"{{root_password.stdout}}\", crypt.mksalt(crypt.METHOD_SHA512)))'"
  register: hashed_root_password
  when: root_password.changed

- lineinfile:
    path: /home/admin/.root_password
    line: "{{root_password}}"
    create: yes
  when: root_password.changed

- name: Set new password for root user
  user:
    name: root
    password: "{{hashed_root_password.stdout}}"
  when: root_password.changed
