---
- name: Ensure python3 and pip3 is installed.
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - python3
    - python3-pip
    - python3-devel

- name: Ensure pip,setuptools and virtualenv are uptodate
  pip:
    name: "{{item}}"
    state: latest
  loop:
    - pip
    - setuptools
    - virtualenv
    - docker
