---
- name: Set password for root user
  user:
    name: root
    password: "{{ lookup('password', '/tmp/.root_password chars=ascii_letters,digits encrypt=sha512_crypt') }}"

- copy:
    src: /tmp/.root_password
    dest: /home/admin/.root_password
    mode: 640
    owner: admin
    group: admin
