---
- name: Create root password
  shell: "head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20"
  args:
    creates: /home/admin/.root_password
  register: root_password

- command: "python -c 'import crypt; print(crypt.crypt(\"{{root_password.stdout}}\", crypt.mksalt(crypt.METHOD_SHA512)))'"
  register: hashed_root_password
  when: root_password.changed

- lineinfile:
    path: /home/admin/.root_password
    line: "{{root_password}}"
    create: yes
  when: root_password.changed

- name: Set password for root user
  user:
    name: root
    password: "{{hashed_root_password.stdout}}"
  when: root_password.changed
