---
- name: Ensure passlib python libary is installed
  pip:
    name: passlib
    executable: pip3.6

- name: Create root password
  shell: "head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20"
  args:
    creates: /home/admin/.root_password
  register: root_password

- command: "python3.6 -c 'from passlib.hash import sha512_crypt; print(sha512_crypt.using(rounds=5000).hash(\"{{root_password.stdout}}\"))'"
  register: hashed_root_password
  when: root_password.changed

- lineinfile:
    path: /home/admin/.root_password
    line: "{{root_password.stdout}}"
    create: true
  when: root_password.changed

- name: Set password for root user
  user:
    name: root
    password: "{{hashed_root_password.stdout}}"
  when: root_password.changed
